openapi: 3.0.1
info:
  title: DLP система для личного пользования
  version: 1.0.0

paths:
  /api/v1/whitelist/:
    get:
      summary: Получение белого списка устройств
      operationId: getUsbWhiteList
      tags: [Белый список устройств]

      responses:
        "200":
          $ref: "#/components/responses/AllowedUsbDeviceListResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalError"
    
    post:
      summary: Добавление устройства в белый список
      operationId: addDeviceToWhiteList
      tags: [Белый список устройств]

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsbDevice"

      responses:
        "201":
          description: OK
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalError"

  /api/v1/whitelist/{id}: 
    delete:
      summary: Удаление устройства из белого списка
      operationId: deleteDeviceFromWhiteList
      tags: [Белый список устройств]

      parameters:
      - $ref: "#/components/parameters/IdPath"

      responses:
        "204":
          $ref: "#/components/responses/NoContent"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"
    
    patch:
      summary: Обновление даты действия устройства в белом списке
      operationId: patchDeviceDateInWhiteList
      tags: [Белый список устройств]

      parameters:
      - $ref: "#/components/parameters/IdPath"

      requestBody:
        $ref: "#/components/requestBodies/ValidToPatch"

      responses:
        "200":
          description: OK
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /api/v1/list/:
    get:
      summary: Получение списка подключённых в данный момент устройств
      operationId: getUsbList
      tags: [Список подключённых устройств]

      responses:
        "200":
          $ref: "#/components/responses/UsbDeviceListResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalError"


components:
  schemas:
    VendorId:
      type: string
      pattern: "^[0-9a-fA-F]{4}$"
      description: Идентификатор вендора
      example: "0781"
    ProductId:
      type: string
      pattern: "^[0-9a-fA-F]{4}$"
      description: Идентификатор устройства
      example: "5567" 
    Serial:
      type: string
      description: Серийный номер
      example: "2222"
    ValidTo:
      type: string
      format: date
      nullable: true
      description: Дата до которой устройство в белом списке включительно. Если не указана, то действует бессрочно.
      example: "2027-03-15"
    Id:
      type: integer
      example: 1
      description: идентификатор из БД
    vendorName:
      type: string
      example: "OnlyDisk"
      description: название вендора для пользователя
    productName:
      type: string
      example: "Netac 179"
      description: название продукта для пользователя
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Неверно значение размера журнала"
        code:
          type: string
          example: "INVALID_INPUT"
    UsbDevice:
      type: object
      required: [vendorId, productId]
      properties:
        vendorId:
          $ref: "#/components/schemas/VendorId"
        productId:
          $ref: "#/components/schemas/ProductId"
        serial:
          nullable: true
          $ref: "#/components/schemas/Serial"
        validTo:
          nullable: true
          $ref: "#/components/schemas/ValidTo"
        vendorName:
          $ref: "#/components/schemas/vendorName"
        productName:
          $ref: "#/components/schemas/productName"
    AllowedUsbDevice:
      allOf:
        - $ref: "#/components/schemas/UsbDevice"
        - type: object
          required: [id]
          properties:
            id:
              $ref: "#/components/schemas/Id"

  responses:
    AllowedUsbDeviceListResponse:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/AllowedUsbDevice"
    UsbDeviceListResponse:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/UsbDevice"
    Unauthorized:
      description: Не авторизован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: Некорректные данные
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalError:
      description: Внутренняя ошибка
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NoContent:
      description: Успешное удаление
    Conflict:
      description: Конфликт
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  parameters:
    IdPath:
      in: path
      name: id
      required: true
      schema:
        $ref: "#/components/schemas/Id"

  requestBodies:
    ValidToPatch:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              validTo:
                $ref: "#/components/schemas/ValidTo"
                nullable: true
