@startuml
left to right direction

' Отключаем серый фон
skinparam backgroundColor White
skinparam actor {
  BackgroundColor White
  BorderColor Black
  FontColor Black
}
skinparam usecase {
  BackgroundColor White
  BorderColor Black
  FontColor Black
}
skinparam arrow {
  Color Black
}

actor "Пользователь" as User
  
usecase "Просмотреть белый список" as UC1
usecase "Добавить устройство в белый список" as UC2
usecase "Удалить устройство из белого списка" as UC3
usecase "Изменить значение поля списка" as UC4
usecase "Просмотреть подключённые устройства" as UC5
  
User -- UC1
User -- UC2
User -- UC3
User -- UC4
User -- UC5

@enduml