services:

  tests:
    image: tests-image:latest

    privileged: true

    volumes:
      - ./coverage-report:/app/coverage-report

  app:
    image: app-image:latest

    ports:
      - "8080:8080"
    
    privileged: true

    volumes:
      - ./logs.txt:/app/logs.txt

  e2e:
    image: e2e-image:latest