@startuml

skinparam linetype ortho

skinparam shadowing false
skinparam roundcorner 8
skinparam monochrome true

skinparam nodesep 80
skinparam ranksep 80
skinparam packagePadding 20

left to right direction

' =========================
' СУЩНОСТИ
' =========================
enum EventType {
  INSERT
  REMOVE
  READ
  WRITE
  EXECUTE
}
package "Essenses" {
    class Device {
    - id: number
    - name: String
    - vendorId: String
    - productId: String
    - serial: String
    - validTo: Date
    }
    class Process {
    - id: number
    - name: String
    - path: String
    - validTo: Date
    }
    class Record {
    - id: number
    - datetime: Date
    - eventype: EventType
    - devName: String
    - vendorId: String
    - productId: String
    - serial: String
    - procName: String
    - procPath: String
    - filePath: String
    - result: enum
    }
    class LogEventOption {
    - type: EventType
    - enabled: boolean
    }
}

Record --> EventType
LogEventOption --> EventType

' =========================
' РЕПОЗИТОРИИ
' =========================
package "Repositories" {
  class SettingsRepository
  class DeviceRepository
  class ProcessRepository
  class LogRepository
}

class DBConnection

SettingsRepository --* DBConnection
DeviceRepository --* DBConnection
ProcessRepository --* DBConnection
LogRepository --* DBConnection

' =========================
' МЕНЕДЖЕРЫ
' =========================
package "Managers" {
  class SettingsManager
  class DeviceManager
  class ProcessManager
  class LogManager
  class PolicyManager {
    +isDeviceAllowed(Device)
    +isProcessAllowed(Process)
  }
}

SettingsManager --* SettingsRepository
DeviceManager --* DeviceRepository
ProcessManager --* ProcessRepository
LogManager --* LogRepository

DeviceManager ..> Device
ProcessManager ..> Process
LogManager ..> Record
SettingsManager ..> LogEventOption

PolicyManager ..> Device
PolicyManager ..> Process

' =========================
' ФАСАД
' =========================
class Facade {
  +execute(command)
}

Facade o-- SettingsManager
Facade o-- DeviceManager
Facade o-- LogManager
Facade o-- ProcessManager

' =========================
' КОМАНДЫ
' =========================
package "Commands" {
  class Command {
    +execute()
  }
  class DeviceCommand
  class SetLogEventsCommand
  class GetLogEventsCommand
  class ProcessCommand
  class GetLogsCommand

  class GetWhiteListDeviceCommand
  class AddDeviceToWhiteListCommand
  class DeleteDeviceFromWhiteListCommand
  class PatchValidToDeivceCommand
  class GetCurrentConnectedDevicesCommand

  class GetWhiteListProcessCommand
  class AddProcessToWhiteListCommand
  class DeleteProcessFromWhiteListCommand
  class PatchValidToProcessCommand
}

Command <|-- DeviceCommand
Command <|-- SetLogEventsCommand
Command <|-- GetLogEventsCommand
Command <|-- ProcessCommand
Command <|-- GetLogsCommand

Facade ..> Command

GetLogsCommand ..> Record
SetLogEventsCommand ..> LogEventOption
GetLogEventsCommand ..> LogEventOption

DeviceCommand <|-- GetWhiteListDeviceCommand
DeviceCommand <|-- AddDeviceToWhiteListCommand
DeviceCommand <|-- DeleteDeviceFromWhiteListCommand
DeviceCommand <|-- PatchValidToDeivceCommand
DeviceCommand <|-- GetCurrentConnectedDevicesCommand

GetCurrentConnectedDevicesCommand ..> Device
PatchValidToDeivceCommand --> Device
AddDeviceToWhiteListCommand --> Device
GetWhiteListDeviceCommand ..> Device

ProcessCommand <|-- GetWhiteListProcessCommand
ProcessCommand <|-- AddProcessToWhiteListCommand
ProcessCommand <|-- DeleteProcessFromWhiteListCommand
ProcessCommand <|-- PatchValidToProcessCommand

PatchValidToProcessCommand --> Process
AddProcessToWhiteListCommand --> Process
GetWhiteListProcessCommand ..> Process

' =========================
' WATCHERS
' =========================
package "Watchers" {
interface Watcher {
    +start()
}

class UdevWatcher
class MountWatcher
class FanotifyWatcher
}

Watcher <|-- UdevWatcher
Watcher <|-- MountWatcher
Watcher <|-- FanotifyWatcher

' =========================
' ОЧЕРЕДЬ
' =========================
class EventQueue {
    +push(event)
    +pop(event)
}

' =========================
' ДИСПЕТЧЕР / WORKER
' =========================
class EventLoop {
    +run()
}

EventLoop --> EventQueue

' =========================
' ГЛАВНЫЙ СЕРВИС (ядро)
' =========================
class DeviceControlService {
    +handleEvent(event)
}

EventLoop --> DeviceControlService

DeviceControlService --> DeviceManager
DeviceControlService --> ProcessManager
DeviceControlService --> LogManager
DeviceControlService --> SettingsManager
DeviceControlService --> PolicyManager

UdevWatcher --> EventQueue
MountWatcher --> EventQueue
FanotifyWatcher --> EventQueue

@enduml